### ISSUE TITLE
Revisar tamaños svg

### ISSUE THREAD

**Issue by vicenlu** [vicenlu/ita-game#69]

**Comment by Bazza6** [comment]
Los iconos del Figma en formato .svg tienen un tamaño enorme (hasta 20MB) y yo no consigo reducirlo. Creo que un buen compromiso es usar un .png. He hecho unas pruebas y bajandolos del figma y poniendo 128pixel de ancho quedan bien y sobre los 20KB.
Que os parece?

<img width="297" alt="Screenshot 2023-02-09 at 17 32 40" src="https://user-images.githubusercontent.com/97785887/217877321-2db2dde7-6712-419c-860c-5bdf3ec12e35.png">

**Comment by JordiNodeJS** [comment]
hombre, la verdad que reduces una barbarídad el tamaño

**Comment by JordiNodeJS** [comment]
sin lugar a dudas utilizaría la versión png

**Comment by Bazza6** [comment]
venga pues por el lunes me encargo de bajar todos los iconos a .png con ese tamaño
